#!/bin/bash
#
# Deploy the application after a git push
#


SITE_ROOT=/sites/tdimeco


# Redirect script output also to a log file
mkdir -p "$SITE_ROOT/log"
exec > >(tee "$SITE_ROOT/log/git.log")
exec 2>&1


# Deploy each pushed branches
while read oldrev newrev branch; do

	echo "---> Starting post-receive hook for $branch at $(date)"

	if [ "$branch" = "refs/heads/master" ]; then
		wwwpath="$SITE_ROOT/www"
		wwwoldpath="$SITE_ROOT/deployment/www-old"
		workpath="$SITE_ROOT/deployment/work-master"
	elif [ "$branch" = "refs/heads/develop" ]; then
		wwwpath="$SITE_ROOT/www-dev"
		wwwoldpath="$SITE_ROOT/deployment/www-dev-old"
		workpath="$SITE_ROOT/deployment/work-dev"
	else
		echo "---> Nothing to do for branch $branch"
		continue
	fi

	# Checkout branch
	echo "---> Checking out modifications from Git..."
	mkdir -p "$workpath"
	git --work-tree="$workpath" --git-dir="$SITE_ROOT/git" checkout -f "$branch"
	if (( $? != 0 )); then
		echo "Git checkout failed for $branch!" >&2
		continue
	fi

	# Compilation
	echo "---> Compiling project..."
	cd "$workpath"

	npm install
	if (( $? != 0 )); then
		echo "NPM installation failed!" >&2
		continue
	fi

	bower install
	if (( $? != 0 )); then
		echo "Bower installation failed!" >&2
		continue
	fi

	grunt dist
	if (( $? != 0 )); then
		echo "Grunt build failed!" >&2
		continue
	fi

	# Backup old site
	echo "---> Backuping old files..."
	rm -fr "$wwwoldpath"
	mv "$wwwpath" "$wwwoldpath"

	# Deploy the new one
	echo "---> Deploying new files..."
	mv "$workpath/dist" "$wwwpath"
	rm -fr "$workpath"

	echo "---> Done!"

done
